# Dependencies
gems: [jekyll-paginate]
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            jeremyblog
tagline:          ''
description:      '『just make the thing simple』'
url:              http://simpleprogram.ne

author:
  name:           'jeremy'
  email:          330526235@qq.com

paginate:      10

# Custom vars
version:          0.0.3         

encoding: utf-8

